import Alert from './Alert.vue';
import Carousel from './Carousel.vue';
import Slider from './Slider.vue';
import Accordion from './Accordion.vue';
import Affix from './Affix.vue';
import Aside from './Aside.vue';
import CheckboxGroup from './CheckboxGroup.vue';
import Checkbox from './Checkbox.vue';
import Datepicker from './Datepicker.vue';
import Dropdown from './Dropdown.vue';
import DropdownLi from './DropdownLi.vue';
import Modal from './Modal.vue';
import Option from './Option.vue';
import Panel from './Panel.vue';
import Popover from './Popover.vue';
import Progressbar from './Progressbar.vue';
import Radio from './Radio.vue';
import RadioGroup from './RadioGroup.vue';
import Select from './Select.vue';
import Tab from './Tab.vue';
import Tabs from './Tabs.vue';
import Tooltip from './Tooltip.vue';
import Typeahead from './Typeahead.vue';
import Navbar from './Navbar.vue';
import Spinner from './Spinner.vue';

export default {
  install(Vue) {
    Vue.component('alert', Alert);
    Vue.component('carousel', Carousel);
    Vue.component('slider', Slider);
    Vue.component('accordion', Accordion);
    Vue.component('affix', Affix);
    Vue.component('bs-aside', Aside);
    Vue.component('checkbox-group', CheckboxGroup);
    Vue.component('checkbox', Checkbox);
    Vue.component('datepicker', Datepicker);
    Vue.component('dropdown', Dropdown);
    Vue.component('dropdown-li', DropdownLi);
    Vue.component('modal', Modal);
    Vue.component('bs-option', Option);
    Vue.component('panel', Panel);
    Vue.component('popover', Popover);
    Vue.component('progressbar', Progressbar);
    Vue.component('radio', Radio);
    Vue.component('radio-group', RadioGroup);
    Vue.component('bs-select', Select);
    Vue.component('tab', Tab);
    Vue.component('tabs', Tabs);
    Vue.component('tooltip', Tooltip);
    Vue.component('typeahead', Typeahead);
    Vue.component('navbar', Navbar);
    Vue.component('spinner', Spinner);
  },
};
