import Alert from './Alert.vue';
import Carousel from './Carousel.vue';
import Slider from './Slider.vue';
import Accordion from './Accordion.vue';
import Affix from './Affix.vue';
import Aside from './Aside.vue';
import CheckboxGroup from './CheckboxGroup.vue';
import Checkbox from './Checkbox.vue';
import Datepicker from './Datepicker.vue';
import Dropdown from './Dropdown.vue';
import DropdownLi from './DropdownLi.vue';
import Modal from './Modal.vue';
import Option from './Option.vue';
import Panel from './Panel.vue';
import Popover from './Popover.vue';
import Progressbar from './Progressbar.vue';
import Radio from './Radio.vue';
import RadioGroup from './RadioGroup.vue';
import Select from './Select.vue';
import Tab from './Tab.vue';
import Tabs from './Tabs.vue';
import Tooltip from './Tooltip.vue';
import Typeahead from './Typeahead.vue';
import Navbar from './Navbar.vue';
import Spinner from './Spinner.vue';

export default {
  install(Vue) {
    Vue.component(Alert, 'alert');
    Vue.component(Carousel, 'carousel');
    Vue.component(Slider, 'slider');
    Vue.component(Accordion, 'accordion');
    Vue.component(Affix, 'affix');
    Vue.component(Aside, 'aside');
    Vue.component(CheckboxGroup, 'checkbox-group');
    Vue.component(Checkbox, 'checkbox');
    Vue.component(Datepicker, 'datepicker');
    Vue.component(Dropdown, 'dropdown');
    Vue.component(DropdownLi, 'dropdown-li');
    Vue.component(Modal, 'modal');
    Vue.component(Option, 'option');
    Vue.component(Panel, 'panel');
    Vue.component(Popover, 'popover');
    Vue.component(Progressbar, 'progressbar');
    Vue.component(Radio, 'radio');
    Vue.component(RadioGroup, 'radio-group');
    Vue.component(Select, 'select');
    Vue.component(Tab, 'tab');
    Vue.component(Tabs, 'tabs');
    Vue.component(Tooltip, 'tooltip');
    Vue.component(Typeahead, 'typeahead');
    Vue.component(Navbar, 'navbar');
    Vue.component(Spinner, 'spinner');
  },
};
